### ISSUE TITLE
Will it work on Aarch64?

### ISSUE THREAD

**Issue by HyperNotAryanX97** [tytydraco/ChArch#2]
> I got this problem while installing Magisk Module.
[magisk_install_log_2021-05-13T08:51:14Z.log](https://github.com/tytydraco/ChArch/files/6470179/magisk_install_log_2021-05-13T08.51.14Z.log)

**Comment by tytydraco** [comment]
Hmm, is charch already installed maybe? I haven't seen that error before.

**Comment by HyperNotAryanX97** [comment]
> Hmm, is charch already installed maybe? I haven't seen that error before.

Yes manually did everything and it got working. Thanks. Btw can you tell me how did you install kde any different steps ? Or Just like simple installation?
